# Generated by Django 5.0.3 on 2025-08-04 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scheduler', '0001_initial'),
        ('Timetable', '0008_alter_broadcast_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#4287f5', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Personal Event Type',
                'verbose_name_plural': 'Personal Event Types',
            },
        ),
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Scheduler.examschedule')),
                ('linked_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Scheduler.lectureschedule')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Portal.personaleventtype')),
            ],
            options={
                'verbose_name': 'Personal Event',
                'verbose_name_plural': 'Personal Events',
                'ordering': ['day', 'time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_institutional_classes', models.BooleanField(default=True)),
                ('show_exams', models.BooleanField(default=True)),
                ('default_view', models.CharField(choices=[('day', 'Day View'), ('week', 'Week View'), ('month', 'Month View')], default='week', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Timetable',
                'verbose_name_plural': 'Personal Timetables',
            },
        ),
    ]
