# Generated by Django 5.0.3 on 2025-07-30 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain letters, digits, spaces, and @/./+/-/_.', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
