# Generated by Django 5.0.3 on 2025-07-31 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_college_building_college_department_college_and_more'),
        ('Users', '0004_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='lecturer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Timetable.lecturer'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Timetable.class'),
        ),
    ]
