# Generated by Django 5.0.3 on 2025-08-02 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='level',
            new_name='class_code',
        ),
    ]
