# Generated by Django 5.0.3 on 2025-08-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0005_lecturer_user'),
        ('Users', '0006_rename_level_studentprofile_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='registered_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='Timetable.course'),
        ),
    ]
