# Generated by Django 5.0.3 on 2025-08-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0008_alter_broadcast_course_and_more'),
        ('Users', '0007_studentprofile_registered_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='Timetable.college'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='registered_courses',
            field=models.ManyToManyField(related_name='students', to='Timetable.course'),
        ),
    ]
