# Generated by Django 5.0.3 on 2025-08-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0008_alter_broadcast_course_and_more'),
        ('Users', '0008_adminprofile_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to='Timetable.college'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='Timetable.college'),
        ),
    ]
