# Generated by Django 5.0.3 on 2025-09-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0008_alter_broadcast_course_and_more'),
        ('Users', '0009_lecturerprofile_college_studentprofile_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='Timetable.college'),
        ),
    ]
